### ISSUE TITLE
Seperate test database

### ISSUE THREAD

**Issue by chucky2305** [lchrusciel/ApiTestCase#138]
Hello together,

i really like this libraby, but i have a problem. Maybe to due missing symfony skills, but i think this library does it on purpose.

In my projects i like to have to databases. One for local development. Lets call this `myproject_dev`. 
I can reset this database any time i want with the same contents. 

For my functional / database tests i want to use a second database. Lets call is `myproject_test`. 

It seems like this library always uses the "default" database, right?
Is there a way, maybe with a setting in `phpunit.xml.dist` to control this behaviour?

Greetings,
Chucky2305

**Comment by lchrusciel** [comment]
You may be right, that `<!--<env name="DATABASE_URL" value="mysql://premium_user:premium_pass@mariadb:3306/premium_int" />-->` may override config. Should be documented.

**Comment by chucky2305** [comment]
I found out that APP_ENV in phpunit.xml.dist is not interpreted in all cases. Especially when you run you code on docker it can happen, that env variables that are stored in the php-container cannot be overwritten by code.

So setting DATABASE_URL in phpunit.xml.dist is one way to go. 
Another is documented here:
https://github.com/symfony/flex/issues/251#issuecomment-364113857

**Comment by lchrusciel** [comment]
So I would consider it as solved
