### ISSUE TITLE
make PolishSymfonyCommunity/SymfonyMockerContainer optional

### ISSUE THREAD

**Issue by videni** [lchrusciel/ApiTestCase#141]
hi, can you make `PolishSymfonyCommunity/SymfonyMockerContainer` optional, seems it is not actively maintained,  also it  doesn't support Symfony4.  it will caused a weird exception when it is used with Symfony 4.2.2, see [stopwatch error after updating symfony to v4.2.2 ](https://github.com/symfony/symfony/issues/29807). please consider make is optional.  

I send a [PR](https://github.com/lchrusciel/ApiTestCase/pull/142)

**Comment by pamil** [comment]
We fixed the stopwatch error by removing `cleanupContainer` method from kernels derived from Sylius (it was used to boost performance, but it has no impact now).

**Comment by videni** [comment]
@pamil,  thanks,  I see, it take lots of time to figure out why that error happened, do you notice  the `MockerContainer ` from  `PolishSymfonyCommunity/SymfonyMockerContainer` repo can not mock private service in Symfony4 anymore ? I created an issue[can't mock private service in symfony4](https://github.com/PolishSymfonyCommunity/SymfonyMockerContainer/issues/11) there, but no one answered.
