### ISSUE TITLE
Support for PHPUnit 8

### ISSUE THREAD

**Issue by pamil** [lchrusciel/ApiTestCase#165]

**Comment by lchrusciel** [comment]
Done in #170

**Comment by emodric** [comment]
Is it too much trouble to ask for PHPUnit 9 support too?

**Comment by lchrusciel** [comment]
Nope, I will deliver it maybe even today. I'm just considering if support for php7.2 is still a required thing tho.

**Comment by emodric** [comment]
Since v5 supports Symfony 4 still, I'd say PHP 7.2 support would be nice to have.

**Comment by lchrusciel** [comment]
That's true, however, PHPUnit 9 is supporting only PHP 7.3 and up. I will need to work a little bit on the testing matrix, but it is not a big problem tho.

**Comment by lchrusciel** [comment]
And it's done: #175 + https://github.com/lchrusciel/ApiTestCase/releases/tag/v5.0.0-beta.3
