### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by emodric** [lchrusciel/ApiTestCase#178]
Hi @lchrusciel !

What is the status of this package? Is it abandoned or would you be okay with allowing PHP 8.0 and releasing a new minor version?

This probably needs a look into dependencies and their support for PHP 8.0.

Thanks!

**Comment by lchrusciel** [comment]
Hi Edi,

It is not abandoned, however, not too much work was done in recent years. I will provide support for PHP8 tho.

Are you blocked by it right now?

Best regards ;)

**Comment by emodric** [comment]
It is indeed one of the 3-4 dependencies still not having PHP 8.0 support in my dependency tree. It is not super critical to have it right now, but it would be nice.

I can help you if you wish.

**Comment by lchrusciel** [comment]
let me take a look into it at the beginning of February and perhaps I will ask you for help

**Comment by emodric** [comment]
Great :)
