### ISSUE TITLE
 The service "nelmio_alice.property_accessor.std" has a dependency on a non-existent service "property_accessor". 

### ISSUE THREAD

**Issue by lamkimphu258** [lchrusciel/ApiTestCase#185]
This is full error while I try to install this package. Do you know how to solve it?

> Script cache:clear returned with error code 1
> 
> !!  
> !!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
> !!                                                                                 
> !!    The service "nelmio_alice.property_accessor.std" has a dependency on a non-  
> !!    existent service "property_accessor". Did you mean this: "nelmio_alice.prop  
> !!    erty_accessor.std"?                                                          
> !!                                                                                 
> !!  
> !! 
> 
> Script @auto-scripts was called via post-update-cmd

**Comment by lchrusciel** [comment]
Hey @lamkimphu258, can you provide me some more details about you issue? Versions of nelmio and PHP for example

**Comment by lamkimphu258** [comment]
Ah I can install it now, it looks like I missed some packages. Thank you @lchrusciel. However, if you want to know, I am using nelmio ^4.4 and php 8.0.9.

**Comment by jelovac** [comment]
Hi,

I also had this error. Apparently the AliceBundle is dependent on symfony/property-access package. If you don't have it the above error will be thrown when executing composer post install scripts such as cache:clear.

It is strange that AliceBundle doesn't have it specified in it's own dependencies.
