### ISSUE TITLE
New changes brakes data provider

### ISSUE THREAD

**Issue by NenadStef** [lchrusciel/ApiTestCase#190]
@lchrusciel With version `5.3` came a problem when using `@dataProvider` annotation.

```
App\Tests\Integration\Controller\Authentication\AuthenticationTest::testShopApiIsProtected
ArgumentCountError: Too few arguments to function App\Tests\Integration\Controller\Authentication\AuthenticationTest::testShopApiIsProtected(), 0 passed in /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1608 and exactly 3 expected
```
The reason for this error is change in commit https://github.com/lchrusciel/ApiTestCase/commit/602a89147dd0cd51700734c4ed25bcafec50777a in file `ApiTestCase.php` in `__construct` method

**Comment by lchrusciel** [comment]
Hey Nenad 👋 

Sorry for the long waiting time, but issue should be fixed with newest release: https://github.com/lchrusciel/ApiTestCase/releases/tag/v5.3.1
