### ISSUE TITLE
SymfonyMockerContainer uses deprecated dependencies. Tests failed

### ISSUE THREAD

**Issue by siwymilek** [lchrusciel/ApiTestCase#78]
> The Symfony\Bundle\MonologBundle\DependencyInjection\Compiler\DebugHandlerPass class is deprecated since version 2.12 and will be removed in 3.0. Use AddDebugLogProcessorPass in FrameworkBundle instead: 1x
    1x in ApiTestCase::createSharedKernel from Lakion\ApiTestCase

**Comment by lchrusciel** [comment]
Not supported anymore
